# Generated by Django 3.1 on 2024-04-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('restaurant_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.IntegerField()),
                ('OrderNumber', models.IntegerField()),
                ('OrderDate', models.DateTimeField()),
                ('ClientAddress', models.CharField(max_length=200)),
                ('TotalOrderPrice', models.FloatField()),
            ],
        ),
    ]
