# Generated by Django 3.1 on 2024-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFoodStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
