# Generated by Django 3.1 on 2024-05-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFoodStore', '0002_auto_20240424_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.BigAutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
