# Generated by Django 3.1 on 2024-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFoodStore', '0003_auto_20240502_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
